version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0  # Use Java 17
    steps:
      - checkout
      - run: ./gradlew clean build --no-daemon

workflows:
  build_and_test:
    jobs:
      - build
