version: 2.1

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:17.0 # OpenJDK 17
    working_directory: ~/repo

jobs:
  build:
    executor: java-executor
    steps:
      - checkout

      # Cache Gradle dependencies
      - restore_cache:
          keys:
            - v1-gradle-{{ checksum "build.gradle" }}
            - v1-gradle-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-gradle-{{ checksum "build.gradle" }}

      # Build Spring Boot JAR
      - run: ./gradlew clean build -x test

      # Save JAR for deploy step
      - persist_to_workspace:
          root: .
          paths:
            - build/libs/*.jar

  deploy:
    executor: java-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Heroku
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
            echo "$HEROKU_API_KEY" | heroku auth:token
            heroku deploy:jar build/libs/*.jar --app book-store-spring-app --jdk 17

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
