version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: ./gradlew build -x test

  deploy:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Install Heroku CLI
          command: curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Deploy to Heroku
          command: |
            echo "machine api.heroku.com login=$HEROKU_EMAIL password=$HEROKU_API_KEY" > ~/.netrc
            echo "machine git.heroku.com login=$HEROKU_EMAIL password=$HEROKU_API_KEY" >> ~/.netrc
            chmod 600 ~/.netrc
            git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME.git
            git push heroku HEAD:main -f

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
